# set vim as default editor
export EDITOR=vim

# for locale
export LANG=en_US.UTF-8
export LC_ALL=ja_JP.UTF-8

# XDG Base Directory Specification's values.
export XDG_CONFIG_HOME=~/.config

# for GNU CLI commands
## for coreutils
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH

## for findutils
export PATH=/usr/local/opt/findutils/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/findutils/libexec/gnuman:$MANPATH

## for gnu-sed
export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/gnu-sed/libexec/gnuman:$MANPATH

## for gnu-tar
export PATH=/usr/local/opt/gnu-tar/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/gnu-tar/libexec/gnuman:$MANPATH

## for gnu-grep
export PATH=/usr/local/opt/grep/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/grep/libexec/gnuman:$MANPATH

## for gnu-grep
export PATH=/usr/local/opt/grep/libexec/gnubin:$PATH
export MANPATH=/usr/local/opt/grep/libexec/gnuman:$MANPATH

# for pyenv
export PYENV_ROOT=$HOME/.pyenv
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

# for rbenv
eval "$(rbenv init -)"

# for nodenv
export NODENV_ROOT=$HOME/.nodenv
export PATH=$NODENV_ROOT/bin:$PATH
eval "$(nodenv init -)"

# for golang
export GOPATH=$HOME/WorkTree/go
export PATH=$GOPATH/bin:$PATH

# for haskell
export PATH=$HOME/.local/bin:$PATH

# for Java
export PATH=$HOME/.jenv/bin:$PATH
eval "$(jenv init -)"

# Aliases
alias ls='ls --color=auto -F'
alias la='ls -a'
alias ll='ls -hl'
alias awk='gawk'
alias grep='grep --color'

if [ -e /usr/local/Cellar/neovim ]; then
  alias vim="/usr/local/bin/nvim"
fi

function trash () {
  mv $@ -t ~/.Trash
}

# Prompt Settings
case $TERM in
  xterm-color|*-256color) color_prompt=yes;;
esac

function _git_branch () {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1]/'
}

function _prompt_setting () {
  local RED="\[\e[38;2;243;27;68m\]"
  local TURQUOISE="\[\e[38;2;64;224;208m\]"
  local WHITE="\[\e[00m\]"
  local BOLD="\[\e[40;1;37m\]"

  case $TERM in
    xterm*) TITLEBAR='\[\e]0;\W\007\]';;
    *)      TITLEBAR="";;
  esac
  local BASE="\u@\h"
  PS1="[${TITLEBAR}${RED}${BASE}${WHITE}] \w ${BOLD}\$(_git_branch)${WHITE}\n\$ "
}

if [ "$color_prompt" = yes ]; then
  _prompt_setting
else
  PS1="\u@\h:\w \$ "
fi
