
# tap repositories and their packages

tap caskroom/cask
cask audacity
cask boostnote
cask evernote
cask fritzing
cask google-chrome
cask google-japanese-ime
cask iterm2
cask java
cask mactex
cask macvim
cask processing
cask skitch
cask skype
cask slack
cask teamviewer
cask virtualbox
cask vlc
cask xquartz

tap caskroom/versions

tap homebrew/bundle

tap homebrew/core
brew autoconf
brew cabal-install
brew cairo
brew coreutils
brew emacs --with-cocoa
brew fftw
brew fish
brew flac
brew fontconfig
brew freetype
brew fswatch
brew gawk
brew gcc
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghc
brew git
brew glib
brew gmp
brew gnu-sed
brew gnu-tar
brew go
brew gobject-introspection
brew harfbuzz
brew html-xml-utils
brew hugo
brew icu4c
brew imagemagick
brew isl
brew jpeg
brew libcroco
brew libevent
brew libffi
brew libgit2
brew libmpc
brew libogg
brew libpng
brew librsvg
brew libsndfile
brew libssh2
brew libtiff
brew libtool
brew libvorbis
brew mad
brew mas
brew mpfr
brew mysql
brew nkf
brew openssl
brew pandoc
brew pango
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew pyenv
brew pyenv-virtualenv
brew python
brew rbenv
brew readline
brew reattach-to-user-namespace
brew ruby-build
brew shared-mime-info
brew sox
brew sqlite
brew ssh-copy-id
brew tmux
brew tree
brew unar
brew unrar
brew utf8proc
brew xz

tap homebrew/dupes
brew grep
brew rsync

tap homebrew/science
brew r

tap homebrew/versions

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 682658836 GarageBand (10.1.3)
appstore 409183694 Keynote (6.6.2)
appstore 539883307 LINE (4.10.2)
appstore 409203825 Numbers (3.6.2)
appstore 409201541 Pages (5.6.2)
appstore 497799835 Xcode (8.1)
appstore 408981434 iMovie (10.1.3)
